# Generated by Django 4.0.3 on 2022-04-18 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문')),
                ('category', models.CharField(choices=[('일반', '일반'), ('계정', '계정'), ('기타', '기타')], max_length=2)),
                ('answer', models.TextField(blank=True, null=True, verbose_name='답변')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_person', models.CharField(max_length=30, verbose_name='최종수정자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종수정일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
        ),
    ]
