# Generated by Django 4.0.3 on 2022-04-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_inquiry_alter_faq_category_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
    ]
